#define WLAN_SSID "YOUR_ROUTER"
#define WLAN_PASS "YOUR_PASS"

#define MQTT_SERVER      "YOUR_SERVER_IP_OR_DOMAIN"
#define MQTT_SERVERPORT  1883
#define MQTT_USERNAME    "USERNAME"
#define MQTT_KEY         "PASSWORD"

#define HOST_NAME        "NAME_OF_ESP_DEVICE_IN_NETWORK"
